### ISSUE TITLE
Messed up display

### ISSUE THREAD

**Issue by jshuadvd** [dorelljames/wp-messenger-customer-chat-plugin#2]
On my site the display is weird. I checked the CSS and have no conflicts with anything else. Can you have a look? Here is a [screenshot](https://imgur.com/a/foeMj) for your viewing. Similarly, whenever I change the default viewing for True or False, it resets and doesn't display the plugin. I have to enter my Page Id again.

Here is the link to my site: https://scimaxdigital.com

**Comment by dorelljames** [comment]
Hi @jshuadvd, I'm sorry but the code here is outdated. I might have to update it to latest. Could you please remove this manually installed plugin and use this one at wordpress.org/plugins/wp-messenger-customer-chat. It's the same plugin but with more features.

**Comment by jshuadvd** [comment]
Hi @dorelljames Thanks for the quick response. I have updated it to the newest version as suggested (1.3.0) and I am still having the same display issues... Also, when I remove my Facebook SDK snippet to use your default loaded on, the plugin doesn't show up. Please advise! Thanks!

**Comment by dorelljames** [comment]
I've checked your site and your theme seems to be applying general CSS on the iframe element.
Check this out: https://www.useloom.com/share/26fe582fb3134728b5fc03ec2fcca7e5

**Comment by jshuadvd** [comment]
Yep - That corrected it! Very strange. Thanks!
