### ISSUE TITLE
Change Text windows

### ISSUE THREAD

**Issue by paulinho1983** [dorelljames/wp-messenger-customer-chat-plugin#3]
Hello,
I entered the chat on my website.
How do I change the text of the Window?

**Comment by dorelljames** [comment]
Hello. I'm sorry but I'm not sure I understand. Could you be a little more specific? Thanks

**Comment by paulinho1983** [comment]
I'm sorry, I'm using a translator.

I put the plugin on my website, it works perfectly. However, I want to change the message that appears in the messenger when I click it to open it.

Now is the message: Hi! How can we help you?

I want another text to appear.

**Comment by paulinho1983** [comment]
I using this code, from this link: 
https://biznessrebels.com/install-facebook-messenger-chat-wordpress/

<script>
 window.fbAsyncInit = function() {
 FB.init({
 appId : 'your-app-id',
 autoLogAppEvents : true,
 xfbml : true,
 version : 'v2.11'
 });
 };

(function(d, s, id){
 var js, fjs = d.getElementsByTagName(s)[0];
 if (d.getElementById(id)) {return;}
 js = d.createElement(s); js.id = id;
 js.src = "https://connect.facebook.net/en_US/sdk.js";
 fjs.parentNode.insertBefore(js, fjs);
 }(document, 'script', 'facebook-jssdk'));
 </script>

**Comment by dorelljames** [comment]
Thanks for elaborating. Anyhow, I'm not sure if it's possible to change the text to something else but I do know it's possible to change its translation. If you try to see on your code. en_US is for English. Please refer to this: https://developers.facebook.com/docs/internationalization
